Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()
$dark=[Drawing.Color]::FromArgb(11,47,36); $felt=[Drawing.Color]::FromArgb(18,59,44); $gold=[Drawing.Color]::FromArgb(201,162,39); $cream=[Drawing.Color]::FromArgb(239,231,211); $red=[Drawing.Color]::FromArgb(158,43,37); $black=[Drawing.Color]::FromArgb(42,39,36); $green=[Drawing.Color]::FromArgb(28,122,82)
$history=New-Object System.Collections.ArrayList; $reds=@(1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36); $buttons=@{}; $cardValues=@(); $triggerBoxes=@(); $betButtons=@(); $betSteps=0,0,0,0,0,0; $triggers=5,5,5,5,5,5; $fib=1,1,2,3,5,8,13,21,34,55,89
$form=New-Object Windows.Forms.Form; $form.Text='DoubleDragon'; $form.ClientSize=New-Object Drawing.Size(760,760); $form.MinimumSize=$form.Size; $form.MaximumSize=$form.Size; $form.BackColor=$dark; $form.StartPosition='CenterScreen'
$main=New-Object Windows.Forms.FlowLayoutPanel; $main.Dock='Fill'; $main.FlowDirection='TopDown'; $main.WrapContents=$false; $main.AutoScroll=$true; $main.Padding=New-Object Windows.Forms.Padding(12); $main.BackColor=$dark; $form.Controls.Add($main)
function P($h){$p=New-Object Windows.Forms.Panel; $p.Size=New-Object Drawing.Size(720,$h); $p.BackColor=$felt; $p.BorderStyle='FixedSingle'; return $p}
function L($s,$x,$y,$c){$l=New-Object Windows.Forms.Label; $l.Text=$s; $l.Location=New-Object Drawing.Point($x,$y); $l.AutoSize=$true; $l.ForeColor=$c; return $l}
function Refresh { $spin.Text="$($history.Count) spins recorded"; $counts=@{};foreach($n in $history){if($counts.ContainsKey($n)){$counts[$n]++}else{$counts[$n]=1}};foreach($n in $buttons.Keys){$buttons[$n].Text=if($counts.ContainsKey($n)){"$n`n$($counts[$n])"}else{"$n"}};foreach($c in @($strip.Controls)){$strip.Controls.Remove($c);$c.Dispose()};$strip.Controls.Add((L 'RECENT SPINS - NEWEST FIRST' 8 4 $gold));$last=@($history|Select-Object -Last 20);[array]::Reverse($last);$x=8;foreach($n in $last){$chip=New-Object Windows.Forms.Label;$chip.Text="$n";$chip.TextAlign='MiddleCenter';$chip.Size=New-Object Drawing.Size(30,30);$chip.Location=New-Object Drawing.Point($x,25);$chip.ForeColor=$cream;$chip.BackColor=if($n -eq 0){$green}elseif($reds -contains $n){$red}else{$black};$strip.Controls.Add($chip);$x+=35};$hits=0,0,0,0,0,0;$lastSeen=-1,-1,-1,-1,-1,-1;for($i=0;$i -lt $history.Count;$i++){ $n=$history[$i];if($n -ne 0){$d=if($n -le 12){0}elseif($n -le 24){1}else{2};$c=3+(($n-1)%3);foreach($g in @($d,$c)){$hits[$g]++;$lastSeen[$g]=$i}}};for($g=0;$g -lt 6;$g++){if($g -lt $cardValues.Count){$abs=if($lastSeen[$g] -lt 0){$history.Count}else{$history.Count-1-$lastSeen[$g]};$cardValues[$g].Text="$($hits[$g]) hits   $abs absent";if($betSteps[$g] -gt 0){$betButtons[$g].Visible=$true;$betButtons[$g].Text="Next bet: $($fib[[math]::Min($betSteps[$g]-1,$fib.Count-1)]) - Stop"}else{$betButtons[$g].Visible=($abs -ge [int]$globalTrigger.SelectedItem);$betButtons[$g].Text="Start betting"}}}
}
function AddSpin($n){if($n -lt 0 -or $n -gt 36){$message.Text='Enter 0 through 36.';return};[void]$history.Add($n);foreach($g in 0..5){if($betSteps[$g] -gt 0){$hit=$false;if($n -ne 0){$d=if($n -le 12){0}elseif($n -le 24){1}else{2};$c=3+(($n-1)%3);$hit=($g -eq $d -or $g -eq $c)};if($hit){$betSteps[$g]=0}else{$betSteps[$g]++;if($betSteps[$g] -gt ($lossLimit.SelectedIndex+1)){$betSteps[$g]=0;$message.Text='Loss limit reached - sequence stopped.'}}}};$message.Text='';Refresh}
$head=New-Object Windows.Forms.Panel;$head.Size=New-Object Drawing.Size(720,45);$head.BackColor=$dark;$title=L 'DoubleDragon' 2 4 $gold;$title.Font=New-Object Drawing.Font('Georgia',21);$spin=L '0 spins recorded' 580 15 $cream;$head.Controls.AddRange([Windows.Forms.Control[]]@($title,$spin));$main.Controls.Add($head)
$gridPanel=P 270;$grid=New-Object Windows.Forms.TableLayoutPanel;$grid.Location=New-Object Drawing.Point(10,10);$grid.Size=New-Object Drawing.Size(696,165);$grid.ColumnCount=13;$grid.RowCount=3;for($i=0;$i -lt 13;$i++){$grid.ColumnStyles.Add((New-Object Windows.Forms.ColumnStyle([Windows.Forms.SizeType]::Percent,7.69)))};for($i=0;$i -lt 3;$i++){$grid.RowStyles.Add((New-Object Windows.Forms.RowStyle([Windows.Forms.SizeType]::Percent,33.3)))}
function NB($n){$b=New-Object Windows.Forms.Button;$b.Text="$n";$b.Tag=$n;$b.Dock='Fill';$b.Margin=New-Object Windows.Forms.Padding(3);$b.FlatStyle='Flat';$b.ForeColor=$cream;$b.BackColor=if($n -eq 0){$green}elseif($reds -contains $n){$red}else{$black};$b.Add_Click({AddSpin([int]$this.Tag)});$buttons[$n]=$b;return $b}
$z=NB 0;$grid.Controls.Add($z,0,0);$grid.SetRowSpan($z,3);$rows=@(@(3,6,9,12,15,18,21,24,27,30,33,36),@(2,5,8,11,14,17,20,23,26,29,32,35),@(1,4,7,10,13,16,19,22,25,28,31,34));for($r=0;$r -lt 3;$r++){for($i=0;$i -lt 12;$i++){$grid.Controls.Add((NB $rows[$r][$i]),$i+1,$r)}};$gridPanel.Controls.Add($grid)
$entry=New-Object Windows.Forms.TextBox;$entry.Location=New-Object Drawing.Point(10,195);$entry.Width=220;$entry.BackColor=$dark;$entry.ForeColor=$cream;$go=New-Object Windows.Forms.Button;$go.Text='Record';$go.Location=New-Object Drawing.Point(240,193);$go.Size=New-Object Drawing.Size(90,29);$go.BackColor=$gold;$go.ForeColor=$dark;$go.Add_Click({$n=0;if([int]::TryParse($entry.Text,[ref]$n)){AddSpin $n;$entry.Text=''}else{$message.Text='Enter 0 through 36.'}});$undo=New-Object Windows.Forms.Button;$undo.Text='Undo';$undo.Location=New-Object Drawing.Point(340,193);$undo.Size=New-Object Drawing.Size(75,29);$undo.Add_Click({if($history.Count){$history.RemoveAt($history.Count-1);Refresh}});$message=L '' 10 235 $red;$gridPanel.Controls.AddRange([Windows.Forms.Control[]]@($entry,$go,$undo,$message));$main.Controls.Add($gridPanel)
$strip=P 65;$main.Controls.Add($strip)
$settings=P 60;$settings.Controls.Add((L 'SETTINGS' 12 8 $gold));$settings.Controls.Add((L 'GLOBAL TRIGGER' 130 8 $gold));$globalTrigger=New-Object Windows.Forms.ComboBox;$globalTrigger.DropDownStyle='DropDownList';[void]$globalTrigger.Items.AddRange([object[]](3,4,5,6,7,8,10));$globalTrigger.SelectedItem=5;$globalTrigger.Location=New-Object Drawing.Point(245,6);$globalTrigger.Width=62;$settings.Controls.Add($globalTrigger);$settings.Controls.Add((L 'STOP LOSS' 365 8 $gold));$lossLimit=New-Object Windows.Forms.ComboBox;$lossLimit.DropDownStyle='DropDownList';[void]$lossLimit.Items.AddRange([object[]]('Step 1 - 1U','Step 2 - 1U','Step 3 - 2U','Step 4 - 3U','Step 5 - 5U','Step 6 - 8U','Step 7 - 13U','Step 8 - 21U','Step 9 - 34U','Step 10 - 55U','Step 11 - 89U'));$lossLimit.SelectedIndex=10;$lossLimit.Location=New-Object Drawing.Point(485,6);$lossLimit.Width=165;$settings.Controls.Add($lossLimit);$settings.Controls.Add((L 'Trigger applies to all 6 groups. Loss limit stops a sequence after that many losing bets.' 12 34 $cream));$globalTrigger.Add_SelectedIndexChanged({Refresh});$lossLimit.Add_SelectedIndexChanged({Refresh});$main.Controls.Add($settings)

$main.Controls.Add((L 'GROUP RECORDS - TOTAL HIT / ABSENCE SINCE LAST APPEARANCE' 0 0 $gold))
$cards=New-Object Windows.Forms.TableLayoutPanel;$cards.Size=New-Object Drawing.Size(720,210);$cards.ColumnCount=3;$cards.RowCount=2;for($i=0;$i -lt 3;$i++){$cards.ColumnStyles.Add((New-Object Windows.Forms.ColumnStyle([Windows.Forms.SizeType]::Percent,33.3)))};for($i=0;$i -lt 2;$i++){$cards.RowStyles.Add((New-Object Windows.Forms.RowStyle([Windows.Forms.SizeType]::Percent,50)))};$names=@('1st Dozen 1-12','2nd Dozen 13-24','3rd Dozen 25-36','Column 1','Column 2','Column 3');for($i=0;$i -lt 6;$i++){$card=P 95;$card.Dock='Fill';$name=L $names[$i] 10 10 $gold;$value=L '0 hits   0 absent' 10 42 $cream;$value.Font=New-Object Drawing.Font('Consolas',13,[Drawing.FontStyle]::Bold);$trigger=New-Object Windows.Forms.ComboBox;$trigger.DropDownStyle='DropDownList';[void]$trigger.Items.AddRange([object[]](3,4,5,6,7,8,10));$trigger.SelectedItem=5;$trigger.Location=New-Object Drawing.Point(215,8);$trigger.Width=105;$trigger.Tag=$i;$trigger.Add_SelectedIndexChanged({$triggers[[int]$this.Tag]=[int]$this.SelectedItem;Refresh});$action=New-Object Windows.Forms.Button;$action.Location=New-Object Drawing.Point(10,66);$action.Size=New-Object Drawing.Size(145,24);$action.BackColor=$gold;$action.ForeColor=$dark;$action.Tag=$i;$action.Add_Click({$g=[int]$this.Tag;if($betSteps[$g] -gt 0){$betSteps[$g]=0}else{$betSteps[$g]=1};Refresh});$card.Controls.AddRange([Windows.Forms.Control[]]@($name,$value,$action));$cardValues+=$value;$triggerBoxes+=$trigger;$betButtons+=$action;$cards.Controls.Add($card,$i%3,[math]::Floor($i/3))};$main.Controls.Add($cards)
$entry.Add_KeyDown({if($_.KeyCode -eq 'Enter'){$go.PerformClick()}});Refresh;[void]$form.ShowDialog()











