(function(){"use strict";
const{RouletteEngine,classify,classifyTwelve,SIDES,TWELVE_SIDES}=window.RouletteCore,{STORAGE_KEY}=window.DashboardStorage;
const red=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]),labels={low:"Low",high:"High",even:"Even",odd:"Odd",red:"Red",black:"Black",dealer:"Dealer",dozen1:"1st Dozen",dozen2:"2nd Dozen",dozen3:"3rd Dozen",column1:"Column 1",column2:"Column 2",column3:"Column 3"};let currentTab="spins";
const fmt=v=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v),time=v=>v?new Date(v).toLocaleString():"—",color=n=>n===0?"green":red.has(n)?"red":"black",chip=n=>`<span class="number ${color(n)}">${n}</span>`,tr=values=>`<tr>${values.map(v=>`<td>${v??"—"}</td>`).join("")}</tr>`;
function getSnapshot(){const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):{version:1,config:{thresholds:Object.fromEntries(SIDES.map(s=>[s,4])),baseUnit:1,startingBankroll:1000},events:[]};}
function triggers(snapshot){const all=[...SIDES,...TWELVE_SIDES],counts=Object.fromEntries(all.map(s=>[s,0])),rows=[];let spin=0,dealer=1;for(const event of snapshot.events){if(event.type==="spin"){spin++;const present=new Set([...classify(Number(event.number)),...classifyTwelve(Number(event.number))]);for(const side of all){const threshold=SIDES.includes(side)?snapshot.config.thresholds[side]:snapshot.config.twelveThresholds[side];if(present.has(side))counts[side]=0;else if(++counts[side]===threshold)rows.push({side,threshold,spin,number:event.number,at:event.at,actions:[]});}}else if(event.type==="dealer-change"){dealer++;rows.push({side:"dealer",threshold:"",spin,number:null,at:event.at,actions:[`Dealer ${dealer} started`]});}else{const action={start:"Bet started",ignore:"Ignored",resume:"Resumed","start-fib":"Bet started","ignore-fib":"Ignored","resume-fib":"Resumed"}[event.type];if(action){const row=[...rows].reverse().find(x=>x.side===event.side&&counts[event.side]>=x.threshold);if(row)row.actions.push(action);}}}return rows.reverse();}
function data(){const snapshot=getSnapshot(),engine=RouletteEngine.fromSnapshot(snapshot);return{snapshot,state:engine.getState(),triggers:triggers(snapshot)};}
function summary(state){const all=[...state.completedSessions,...state.completedFibSessions],completed=all.filter(s=>s.reason==="won"||s.reason==="target-reached").length,stopped=all.filter(s=>s.reason==="max-bets-stopped").length,burst=all.filter(s=>s.reason==="max-stage-loss").length,totalPL=state.realizedPL+state.fibRealizedPL;return[["Total spins",state.spinCount],["Bet sessions",all.length],["Completed / Stopped / Burst",`${completed} / ${stopped} / ${burst}`],["Combined P/L",fmt(totalPL),totalPL>=0?"positive":"negative"]].map(([l,v,c=""])=>`<div class="summary-card"><span>${l}</span><strong class="${c}">${v}</strong></div>`).join("");}
function table(tab,d){
 const s=d.state,all=[...s.completedSessions,...s.completedFibSessions];
 if(tab==="spins")return{h:["Spin","Date / Time","Number","Colour","Parity","Range"],r:[...s.spins].reverse().map(x=>{const p=classify(x.number);return[x.index,time(x.at),chip(x.number),color(x.number),p.find(v=>v==="odd"||v==="even")||"Zero",p.find(v=>v==="low"||v==="high")||"Zero"]})};
 if(tab==="triggers")return{h:["Trigger spin","Date / Time","Side","Threshold","Number","Actions"],r:d.triggers.map(x=>[x.spin,time(x.at),labels[x.side],x.threshold,x.side==="dealer"?"—":chip(x.number),x.actions.join(" → ")||"Waiting"])};
 if(tab==="sessions")return{h:["Session","Side","System","Start spin","End spin","Stages","Result","P/L","Numbers"],r:[...all].reverse().map(x=>[x.id,labels[x.side],x.system==="fibonacci"?"Fibonacci · 2:1":x.system==="two-win"?`Two-Win Reset · ${x.tableRule==="la-partage"?"La Partage":"Standard"}`:x.tableRule==="la-partage"?"Martingale · La Partage":"Martingale",x.startSpin,x.endSpin,x.stakes.length,x.reason==="max-stage-loss"?"Burst":x.reason==="max-bets-stopped"?"Stopped":x.reason==="target-reached"?"Target reached":x.reason==="won"?"Won":"Cancelled",fmt(x.pl),x.numbers.join(", ")])};
 if(tab==="steps"){const rows=[];[...all].reverse().forEach(x=>x.stakes.forEach((stake,i)=>{const outcome=x.outcomes?.[i]||(x.reason==="won"&&i===x.stakes.length-1?"win":"loss"),running=x.plChanges?x.plChanges.slice(0,i+1).reduce((sum,v)=>sum+v,0):0;rows.push([x.id,labels[x.side],i+1,fmt(stake),x.startSpin+i,chip(x.numbers[i]),outcome==="half-loss"?"Half-loss":outcome==="win"?"Win":"Loss",fmt(running)]);}));return{h:["Session","Side","Stage","Stake","Spin","Number","Outcome","Running P/L"],r:rows};}
 return{h:["Metric","Even-money","12-number"],r:[["Starting bankroll",fmt(s.config.startingBankroll),fmt(s.config.twelveStartingBankroll)],["Current bankroll",fmt(s.bankroll),fmt(s.fibBankroll)],["Realized P/L",fmt(s.realizedPL),fmt(s.fibRealizedPL)],["Active P/L",fmt(s.activePL),fmt(s.fibActivePL)],["Active exposure",fmt(s.exposure),fmt(s.fibExposure)],["Unit value",fmt(s.config.baseUnit),fmt(s.config.twelveBaseUnit)],["System",s.config.evenSystem==="two-win"?`Two-Win Reset · ${s.config.tableRule==="la-partage"?"La Partage":"Standard"}`:s.config.tableRule==="la-partage"?"Martingale · La Partage":"Martingale","Fibonacci · 2:1"],["Completed sessions",s.completedSessions.length,s.completedFibSessions.length]]};
}
function render(){try{const d=data(),t=table(currentTab,d);document.querySelector("#summary").innerHTML=summary(d.state);document.querySelector("#table-head").innerHTML=`<tr>${t.h.map(x=>`<th>${x}</th>`).join("")}</tr>`;document.querySelector("#table-body").innerHTML=t.r.map(tr).join("");document.querySelector("#empty-state").hidden=t.r.length>0;document.querySelector(".table-wrap").hidden=t.r.length===0;document.querySelector("#saved-status").textContent=`${d.state.spinCount} spins saved locally`;}catch(e){document.querySelector("#saved-status").textContent="Saved data could not be read";}}
document.querySelector(".tabs").addEventListener("click",e=>{const b=e.target.closest("[data-tab]");if(!b)return;currentTab=b.dataset.tab;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));render();});document.querySelector("#refresh-button").addEventListener("click",render);window.addEventListener("storage",render);render();
})();
